<?php
use Site\Configuration;
use Model\Arraymodel\EventList;

use Pes\View\Renderer\PhpTemplateRendererInterface;
use Model\Entity\PaperAggregatePaperContentInterface;

$headline = 'Pracovní pozice';
$perex = '';

//template:
//    repeat('vnitřek', $kategorie]
//$tag = [
//    1 => 'výroba/dělnická',
//    2 => 'administrativa/THP',
//    3 => 'technická',
//    4 => 'manažerská/vedoucí'
//];
//$kvalifikace = [
//    1 => 'Bez omezení',
//    2 => 'ZŠ',
//    3 => 'SOU bez maturity',
//    4 => 'SOU s maturitou',
//    5 => 'SŠ',
//    5 => 'VOŠ / Bc.',
//    5 => 'VŠ',
//];

$pracovniPozice = [
    ['nazev' => 'Elektro projektant','kategorie' => [2,3],'mistoVykonu' => 'Plzeň','vzdelani' =>5,'popisPozice' => '<p>  • Podílet se na vzniku Hi-Tech technologie pro nápojový průmysl. </p>  <p>  • V programech Racos nebo E-plan zpracovávat návrhy rozvaděčů v projektech nápojových linek. </p>  <p>  • Svoji práci pečlivě dokumentovat v SAP. </p>  <p>  • Pomocí emailu či telefonu komunikovat s německými kolegy z mateřské firmy. </p>  <p>  • Spolupracovat v týmu přátelských a profesionálních projektantů. </p>  <p>  • Jezdit na občasné služební cesty. </p>','pozadujeme' => ['<p>• Znalost některého z CAD systémů, ve kterém jsi již projektoval/a.</p>  <p>• Němčinu, připadně angličtinu se kterou se dokážeš domluvit s německými kolegy.</p>  <p>• Chuť k případným služebním cestám do Německa.</p>'],'nabizime' => ['<p>• Flexibilní pracovní dobu 38,5 hodiny týdně</p>  <p>• Moderní pracovní prostředí</p>  <p>• 25 dnů dovolené, za každých 5 odpracovaných let 1 den dovolené navíc</p>  <p>• Jazykové kurzy přímo na pracovišti a zdarma</p>  <p>• Home office</p>  <p>• Dotované stravování, i na home office</p>  <p>• Příspěvek na penzijní pojištění 1000 Kč za měsíc</p>  <p>• Po roce příspěvek na volnočasové aktivity 6000 Kč za rok</p>  <p>• Prémie za pracovní výročí; a další</p>']],
    ['nazev' => 'Strojní konstruktér','kategorie' => [2,3],'mistoVykonu' => 'Plzeň','vzdelani' =>5,'popisPozice' => '<p>  •Kreslit v SolidEdge či AutoCad návrhy plniček, etiketovaček a dalších částí nápojové linky </p>  <p>  • Svoji práci pečlivě dokumentovat v SAP </p>  <p>  • Pomocí emailu či telefonu komunikovat s německými kolegy z mateřské firmy </p>  <p>  • Spolupracovat v týmu nadšených konstruktérů </p>  <p>  • Jezdit na občasné služební cesty do Německa </p>','pozadujeme' => ['<p>• Znalost 3D konstrukčního systému, ve kterém jsi již projektoval/a (SolidEdge, SolidWorks, NX)</p>  <p>• Němčinu, připadně angličtinu se kterou se dokážeš domluvit s německými kolegy</p>  <p>• Chuť k případným služebním cestám do Německa. Nejvíce jezdíme do Neutraublingu</p>'],'nabizime' => ['<p>• Flexibilní pracovní dobu 38,5 hodiny týdně</p>  <p>• Moderní pracovní prostředí</p>  <p>• 25 dnů dovolené, za každých 5 odpracovaných let 1 den dovolené navíc</p>  <p>• Jazykové kurzy přímo na pracovišti a zdarma</p>  <p>• Home office</p>  <p>• Dotované stravování, i na home office</p>  <p>• Příspěvek na penzijní pojištění 1000 Kč za měsíc</p>  <p>• Po roce příspěvek na volnočasové aktivity 6000 Kč za rok</p>  <p>• Prémie za pracovní výročí; a další</p>']],
    ['nazev' => 'PLC programátor','kategorie' => [2,3],'mistoVykonu' => 'Plzeň','vzdelani' =>5,'popisPozice' => '<p>  • Sestavovat, adaptovat a upravovat program pro funkční celky nápojové linky a jejich vizualizaci </p>  <p>  • Programovat a konfigurovat bezpečnostní systémy v oblasti automatizace </p>  <p>  • Konfigurovat hardware a komunikaci mezi částmi linky </p>  <p>  • Při simulaci testovat a ladit funkci svého programu </p>  <p>  • Pracovat v klidném prostředí s minimem služebních cest </p>  <p>  • Spolupracovat s kolegy z naší mateřské firmy Krones </p>  <p>  • Jezdit na občasné služební cesty do Neutraublingu </p>','pozadujeme' => ['<p>• Vzdělání zaměřené na automatizaci a elektrotechniku</p>  <p>• Zkušenosti s programováním v Simatic S7 a TIA-Portál</p>  <p>• Znalost principů automatizace a souvisejících el. zařízení</p>  <p>• Němčinu, případně angličtinu se kterou se bez problémů domluvíš s německým kolegou ohledně projektu</p>  <p>• Analytické schopnosti</p>  <p>• Řidičský průkaz sk. B výhodou</p>'],'nabizime' => ['<p>• Flexibilní pracovní dobu 38,5 hodiny týdně</p>  <p>• Moderní pracovní prostředí</p>  <p>• 25 dnů dovolené, za každých 5 odpracovaných let 1 den dovolené navíc</p>  <p>• Jazykové kurzy přímo na pracovišti a zdarma</p>  <p>• Home office</p>  <p>• Dotované stravování, i na home office</p>  <p>• Příspěvek na penzijní pojištění 1000 Kč za měsíc</p>  <p>• Po roce příspěvek na volnočasové aktivity 6000 Kč za rok</p>  <p>• Prémie za pracovní výročí; a další</p>']],
    ['nazev' => 'Cloud developer','kategorie' => [2,3],'mistoVykonu' => 'Plzeň','vzdelani' =>5,'popisPozice' => '<p>  • Budovat nové cloudové AWS řešení pro pivovary a další zákazníky </p>  <p>  • Vyvíjet back-endové služby a webový front-end </p>  <p>  • Rozvoj digitalizace nápojových linek pro světové značky </p>','pozadujeme' => ['<p>• Znalost programování v Python</p>  <p>• Zájem o cloudové technologie</p>  <p>• Znalost některého z frameworků: Angular, TypeScript, Go, Node, Bootstrap</p>  <p>• Zkušenosti s relačními nebo NoSQL databázemi</p>  <p>• Zkušenosti s Docker, Git, Jenkins, Linux, …</p>  <p>• Chuť naučit se další věci</p>'],'nabizime' => ['<p>• Flexibilní pracovní dobu 38,5 hodiny týdně</p>  <p>• Moderní pracovní prostředí</p>  <p>• 25 dnů dovolené, za každých 5 odpracovaných let 1 den dovolené navíc</p>  <p>• Jazykové kurzy přímo na pracovišti a zdarma</p>  <p>• Home office</p>  <p>• Dotované stravování, i na home office</p>  <p>• Příspěvek na penzijní pojištění 1000 Kč za měsíc</p>  <p>• Po roce příspěvek na volnočasové aktivity 6000 Kč za rok</p>  <p>• Prémie za pracovní výročí;  a další</p>']],
    ['nazev' => 'C# programátor','kategorie' => [2,3],'mistoVykonu' => 'Plzeň','vzdelani' =>5,'popisPozice' => '<p>  • Vyvíjet software pro řízení výroby v nápojovém průmyslu za použití programovacího jazyka C# a .NET frameworku </p>  <p>  • To, co vyvineš, si také otestuješ – automatizované testy </p>  <p>  • Práce s real-time daty </p>  <p>  • Rozvoj digitalizace nápojových linek pro světové značky </p>  <p>  • Používat technologie a produkty od společnosti Microsoft pro vývoj (SQL Server, Azure Cloud, SSRS atd.) </p>  <p>  • Úzká spolupráce s R&amp;D oddělením v Německu </p>  <p>  • Podílet se na agilním vývoji (SCRUM) </p>  <p>  • Pracovat v 4 - 6členných týmech na různých částech systémů (database, services, UI, komunikace s jinými systémy – ERP, PLC) </p>','pozadujeme' => ['<p>• Znalost .NET a zkušenosti s objektovým programováním</p>  <p>• Angličtinu nebo němčinu na takové úrovni, aby ses mohl/a domluvit s německými kolegy</p>  <p>• Zodpovědný přístup k práci – svědomitě vykonávat veškeré náležitosti spojené s prací a procesem scrumu</p>  <p>• Výhodou znalost python či javascript</p>  <p>• Samostatnost – přesto, že pracujeme v týmu, je občas potřeba dohledat si některé informace a řešit problémy samostatně</p>'],'nabizime' => ['<p>• Flexibilní pracovní dobu 38,5 hodiny týdně</p>  <p>• Moderní pracovní prostředí</p>  <p>• 25 dnů dovolené, za každých 5 odpracovaných let 1 den dovolené navíc</p>  <p>• Jazykové kurzy přímo na pracovišti a zdarma</p>  <p>• Home office</p>  <p>• Dotované stravování, i na home office</p>  <p>• Příspěvek na penzijní pojištění 1000 Kč za měsíc</p>  <p>• Po roce příspěvek na volnočasové aktivity 6000 Kč za rok</p>  <p>• Prémie za pracovní výročí; a další</p>']],
    ['nazev' => 'Operativní nákupčí','kategorie' => [2],'mistoVykonu' => 'Plzeň','vzdelani' =>5,'popisPozice' => '<p>  • Jednat se zákazníkem a zahraničními dodavateli (komunikace v německém jazyce telefonicky i po emailu) </p>  <p>  • Tvorbu objednávek, jejich kontrolu a evidenci v programu SAP </p>  <p>  • Kontrolovat dodací termíny </p>  <p>  • Evidovat změny </p>  <p>  • Zpracovávat upomínky a reklamace </p>','pozadujeme' => ['<p>• Zkušenosti z nákupu</p>  <p>• Vyjednávací schopnosti</p>  <p>• Schopnost se rychle rozhodovat</p>  <p>• Dobrou znalost MS office</p>  <p>• Komunikativní znalost německého jazyka</p>  <p>• Pečlivost a komunikativnost</p>  <p>• Ochotu učit se</p>'],'nabizime' => ['<p>• Flexibilní pracovní dobu 38,5 hodiny týdně</p>  <p>• Moderní pracovní prostředí</p>  <p>• 25 dnů dovolené, za každých 5 odpracovaných let 1 den dovolené navíc</p>  <p>• Jazykové kurzy přímo na pracovišti a zdarma</p>  <p>• Home office</p>  <p>• Dotované stravování, i na home office</p>  <p>• Příspěvek na penzijní pojištění 1000 Kč za měsíc</p>  <p>• Po roce příspěvek na volnočasové aktivity 6000 Kč za rok</p>  <p>• Prémie za pracovní výročí; a další</p>']],
    ['nazev' => 'Strategický nákupčí','kategorie' => [2],'mistoVykonu' => 'Plzeň','vzdelani' =>5,'popisPozice' => '<p>  • Jednat se zákazníkem a zahraničními dodavateli (komunikace v německém jazyce telefonicky i po emailu) </p>  <p>  • Tvorbu objednávek, jejich kontrolu a evidenci v programu SAP </p>  <p>  • Kontrolovat dodací termíny </p>  <p>  • Evidovat změny </p>  <p>  • Zpracovávat upomínky a reklamace </p>','pozadujeme' => ['<p>• Zkušenosti z nákupu</p>  <p>• Prozákaznické jednání</p>  <p>• Vyjednávací schopnosti</p>  <p>• Dobrou znalost MS office</p>  <p>• Komunikativní znalost německého jazyka</p>  <p>• Pečlivost a komunikativnost</p>  <p>• Ochotu učit se</p>'],'nabizime' => ['<p>• Flexibilní pracovní dobu 38,5 hodiny týdně</p>  <p>• Moderní pracovní prostředí</p>  <p>• 25 dnů dovolené, za každých 5 odpracovaných let 1 den dovolené navíc</p>  <p>• Jazykové kurzy přímo na pracovišti a zdarma</p>  <p>• Home office</p>  <p>• Dotované stravování, i na home office</p>  <p>• Příspěvek na penzijní pojištění 1000 Kč za měsíc</p>  <p>• Po roce příspěvek na volnočasové aktivity 6000 Kč za rok</p>  <p>•Prémie za pracovní výročí; a další</p>']],
    ['nazev' => 'Finanční controller','kategorie' => [2],'mistoVykonu' => 'Plzeň','vzdelani' =>5,'popisPozice' => '<p>  • Tvořit hodnocení v oblasti controllingu </p>  <p>  • Připravovat dokumentaci pro vnitropodnikové účetnictví (Transfer Pricing) </p>  <p>  • Stanovovat daňové výsledky montážních projektů v rámci celého světa </p>  <p>  • Průběžnou dokumentaci převodních cen </p>  <p>  • Interní vyúčtování administrativních služeb </p>  <p>  • Projekty v oblasti převodních cen </p>  <p>  • Podporovat oddělení v ostatních daňových záležitostech </p>','pozadujeme' => ['<p>• Vzdělání obchodního směru, nebo podobné</p>  <p>• Minimálně 2 roky praxe v oboru</p>  <p>• Znalost mezinárodního práva a pokynů OECD v oblasti převodních cen</p>  <p>• Pokročilá znalost programů MS office</p>  <p>• Znalost programu SAP výhodou</p>  <p>• Anglický jazyk na pokročilé úrovni</p>  <p>• Znalost německého jazyku výhodou</p>  <p>• Ochotu cestovat do mateřské společnosti v Neutrablingu</p>'],'nabizime' => ['<p>• Flexibilní pracovní dobu 38,5 hodiny týdně</p>  <p>• Moderní pracovní prostředí</p>  <p>• 25 dnů dovolené, za každých 5 odpracovaných let 1 den dovolené navíc</p>  <p>• Jazykové kurzy přímo na pracovišti a zdarma</p>  <p>• Home office</p>  <p>• Dotované stravování, i na home office</p>  <p>• Příspěvek na penzijní pojištění 1000 Kč za měsíc</p>  <p>• Po roce příspěvek na volnočasové aktivity 6000 Kč za rok</p>  <p>• Prémie za pracovní výročí; a další</p>']],
    
]


?>

    <div id="pracovni-pozice">
       <?php
       
        
        include Configuration::componentControler()['templates']."presenter-job/template.php";
        ?>
    </div>