<?php
use Site\Configuration;
use Model\Arraymodel\EventList;

use Pes\View\Renderer\PhpTemplateRendererInterface;
use Model\Entity\PaperAggregatePaperContentInterface;

$headline = 'Pracovní pozice';
$perex = '';

//template:
//    repeat('vnitřek', $kategorie]
//$tag = [
//    1 => 'výroba/dělnická',
//    2 => 'administrativa/THP',
//    3 => 'technická',
//    4 => 'manažerská/vedoucí'
//];
//$kvalifikace = [
//    1 => 'Bez omezení',
//    2 => 'ZŠ',
//    3 => 'SOU bez maturity',
//    4 => 'SOU s maturitou',
//    5 => 'SŠ',
//    5 => 'VOŠ / Bc.',
//    5 => 'VŠ',
//];

$pracovniPozice = [
    ['nazev' => 'Operátor výroby','kategorie' => [1],'mistoVykonu' => 'Rakovník','vzdelani' =>1,'popisPozice' => 'Práce v čistém a nehlučném prostředí. Montáž klimatizačních jednotek a kontrolních panelú do aut.','pozadujeme' => ['<p>• základní vzdělání</p>  <p>• manuální zručnost</p>  <p>• ochotu učit se novým věcem</p>  <p>• spolehlivost</p>'],'nabizime' => ['<p>• nástupní mzdu 23500 Kč, průměrnou mzdu s příplatky za směny až 30000 Kč měsíčně</p>  <p>• 6 týdnů dovolené</p>  <p>• Měsíční a pololetní bonus</p>  <p>• Podporu mobility (náhrada výdajů na dojíždění)</p>  <p>• Příspěvek na penzijní připojištění 5 % z hrubé mzdy</p>  <p>• Dotovanou kantýnu</p>  <p>• Příspěvek na volnočasové aktivity ve formě poukázek FlexiPass</p>  <p>• Svozovou dopravu zdarma</p>']],
    ['nazev' => 'Operátor výroby','kategorie' => [1],'mistoVykonu' => 'Humpolec','vzdelani' =>1,'popisPozice' => 'Práce v čistém a nehlučném prostředí. Montáž kompresorů klimatizace do aut.','pozadujeme' => ['<p>• základní vzdělání</p>  <p>• manuální zručnost</p>  <p>• ochotu učit se novým věcem</p>  <p>• spolehlivost</p>'],'nabizime' => ['<p>• nástupní mzdu 20500 Kč, průměrnou mzdu s příplatky za směny až 25500 Kč měsíčně</p>  <p>• 6 týdnů dovolené</p>  <p>• Měsíční a pololetní bonus</p>  <p>• Příspěvek na penzijní připojištění 5 % z hrubé mzdy</p>  <p>• Dotovanou kantýnu</p>  <p>• Příspěvek na volnočasové aktivity ve formě poukázek FlexiPass</p>  <p>• Svozovou dopravu zdarma</p>']],
    ['nazev' => 'Operátor výroby','kategorie' => [1],'mistoVykonu' => 'Žebrák','vzdelani' =>1,'popisPozice' => 'Práce v čistém a nehlučném prostředí. Montáž výparníků klimatizace a chladičů baterií do aut.','pozadujeme' => ['<p>• základní vzdělání</p>  <p>• manuální zručnost</p>  <p>• ochotu učit se novým věcem</p>  <p>• spolehlivost</p>'],'nabizime' => ['<p>• nástupní mzdu 22000 Kč, průměrnou mzdu s příplatky za směny až 29000 Kč měsíčně</p>  <p>• 6 týdnů dovolené</p>  <p>• Měsíční a pololetní bonus</p>  <p>• Podporu mobility (náhrada výdajů na dojíždění)</p>  <p>• Příspěvek na penzijní připojištění 5 % z hrubé mzdy</p>  <p>• Dotovanou kantýnu</p>  <p>• Svozovou dopravu zdarma</p>  <p>• Příspěvek na volnočasové aktivity ve formě poukázek FlexiPass</p>']],
    ['nazev' => 'Operátor výroby','kategorie' => [1],'mistoVykonu' => 'Podbořany','vzdelani' =>1,'popisPozice' => 'Práce v čistém a nehlučném prostředí. Montáž hydraulických spojkových ložisek a komponent brzdy do aut.','pozadujeme' => ['<p>• základní vzdělání</p>  <p>• manuální zručnost</p>  <p>• ochotu učit se novým věcem</p>  <p>• spolehlivost</p>'],'nabizime' => ['<p>• mzdu s benefity 26500 Kč</p>  <p>• 28 dní volna</p>  <p>• 100%-ně dotované stravenky</p>  <p>• Příspěvek na penzijní připojištění</p>']],
    ['nazev' => 'Systémový inženýr - produkty pro elektromobily','kategorie' => [3],'mistoVykonu' => 'Praha','vzdelani' =>7,'popisPozice' => 'Ve vývojovém centru Valeo v Praze navrhujeme klimatizační jednotky do aut již od roku 2002. V roce 2020 vznikl v Praze nový vývojový tým zabývající se vysokonapěťovými komponenty do klimatizací elektromobilů a do systému chlazení jejich baterií. Tito mechaničtí, testovací a systémoví inženýři posílají své vyvinuté díly do 28 výrobních závodů po celém světě. Blíže pak spolupracují s vývojovým centrem ve francouzském La Verrière. Své projekty si řídí sami a vzhledem k inovativnosti jejich produktů jsou průkopníky na trhu elektromobility.','pozadujeme' => ['<p>• vysokoškolské vzdělání v oblasti elektroniky</p>  <p>• zkušenost se systémovým inženýrstvím nebo s vývojem elektronických součástek</p>  <p>•  angličtinu na komunikativní úrovni</p>'],'nabizime' => ['<p>• 6 týdnů dovolené</p>  <p>• Možnost home-office</p>  <p>• Bonusy závislé na výsledcích týmu</p>  <p>• Podporu mobility (náhrada výdajů na dojíždění, stěhování, dočasné ubytování)</p>  <p>• Příspěvek na penzijní připojištění 5 % z hrubé mzdy</p>  <p>• Stravenky a výbornou kantýnu</p>  <p>• Příspěvek na sport ve formě poukázek FlexiPass nebo Multisport karty</p>  <p>• Technická a jazyková školení</p>']],
    ['nazev' => 'Technický projektový manažer','kategorie' => [4],'mistoVykonu' => 'Praha','vzdelani' =>7,'popisPozice' => 'Ve vývojovém centru Valeo v Praze navrhujeme klimatizační jednotky do aut již od roku 2002. V roce 2020 vznikl v Praze nový vývojový tým zabývající se vysokonapěťovými komponenty do klimatizací elektromobilů a do systému chlazení jejich baterií. Tito mechaničtí, testovací a systémoví inženýři posílají své vyvinuté díly do 28 výrobních závodů po celém světě. Blíže pak spolupracují s vývojovým centrem ve francouzském La Verrière. Své projekty si řídí sami a vzhledem k inovativnosti jejich produktů jsou průkopníky na trhu elektromobility.','pozadujeme' => ['<p>• zkušenost min. 5 let v automobilovém průmyslu</p>  <p>• vysokoškolské technické vzdělání (elektronika nebo software nebo automatizace nebo robotika, mechatronika)</p>  <p>• zkušenost min. 3 let s vedením projektu v automotive</p>  <p>• výbornou angličtinu pro komunikaci na denní bázi</p>  <p>• řidičský průkaz a ochotu cestovat za zákazníky po celé Evropě</p>'],'nabizime' => ['<p>• 6 týdnů dovolené</p>  <p>• Možnost home-office</p>  <p>• Bonusy závislé na výsledcích týmu</p>  <p>• Podporu mobility (náhrada výdajů na dojíždění, stěhování, dočasné ubytování)</p>  <p>• Příspěvek na penzijní připojištění 5 % z hrubé mzdy</p>  <p>• Stravenky a výbornou kantýnu</p>  <p>• Příspěvek na sport ve formě poukázek FlexiPass nebo Multisport karty</p>  <p>• Technická a jazyková školení</p>']],
    ['nazev' => 'Elektrotechnik','kategorie' => [3],'mistoVykonu' => 'Žebrák','vzdelani' =>3,'popisPozice' => '<p>• Provádění oprav většího rozsahu za pomoci PC</p>  <p>• Práce v automatizované výrobě</p>  <p>• Programování PLC</p>  <p>• Odstraňování nedostatků a závad formou technické podpory</p>  <p>• Návrh a realizace zdokonalení technické stránky strojů</p>  <p>• Kontrola dokumentace preventivní údržby</p>  <p>• Vedení technické dokumentace</p>  <p>• Odpovědnost za svěřené nářadí směny údržby</p>  <p>• Metodické vedení údržbářů na směně</p>','pozadujeme' => ['<p>• Praxe v oblasti elektro údržby nebo elektro servisu</p>  <p>• Vyhláška 50, minimálně §6</p>  <p>• Obecný přehled v oborech strojírenství nebo mechaniky</p>  <p>• Zájem o robotiku a programování</p>  <p>• Chuť do práce, zodpovědnost, spolehlivost a pečlivost</p>  <p>• Vztah k technice a manuální zručnost</p>  <p>• Základní znalost volně programovatelných automatů výhodou</p>  <p>• Schopnost samostatně se rozhodovat</p>  <p>• Všeobecný přehled o opravárenských nástrojích</p>'],'nabizime' => ['<p>• 6 týdnů dovolené</p>  <p>• Bonusy závislé na výsledcích týmu</p>  <p>• Podpora na dojíždění: 3Kč/km (max. 6 000 Kč/měsíc)</p>  <p>• Příspěvek na penzijní připojištění 5 % z hrubé mzdy</p>  <p>• Dotovanou kantýnu</p>  <p>• Příspěvek na sport a volnočasové aktivity ve formě poukázek FlexiPass, v hodnotě 20000 Kč ročně</p>  <p>• Svozovou autobusovou dopravu zdarma</p>']],
    ['nazev' => 'Elektrotechnik','kategorie' => [3],'mistoVykonu' => 'Rakovník','vzdelani' =>3,'popisPozice' => '<p>• Řešení poruch a preventivní údržba na plně automatických linkách</p>  <p>• Zásahy na všech elektrických poruchách a závadách automatiky/pneumatiky</p>  <p>• Analýza skutečné příčiny poruchy a realizace dlouhodobé nápravné akce</p>  <p>• Komunikace s dodavateli při řešení poruchy a zajištění servisu</p>  <p>• Zlepšení výkonnosti a ostatních ukazatelů zařízení</p>  <p>• Analýza provozu a spolehlivosti zařízení na základě indikátorů</p>  <p>• Zlepšení produktivity na zařízení</p>  <p>• Definice náhradních dílů a dodržování správy náhradních dílů</p>','pozadujeme' => ['<p>• SŠ vzdělání v elektro směru / nebo SOU vzdělání s min 3 letou praxí</p>  <p>• Platná vyhláška 50/1978 Sb., min. §6</p>  <p>• Znalost a práce s elektrodokumentací</p>  <p>• Znalost pneumatiky a automatizace výhodou</p>  <p>• Znalost robotů výhodou</p>  <p>• Spolehlivost, pečlivost, zodpovědnost, flexibilita, systematický přístup, analytické myšlení, týmový hráč</p>  <p>• Znalost AJ nebo NJ výhodou</p>  <p>Řidičský průkaz sk. B</p>'],'nabizime' => ['<p>• 6 týdnů dovolené</p>  <p>• Pracovní oděv</p>  <p>• Firemní jídelnu s dotovaným stravným (obědy i večeře)</p>  <p>• Flexipassy pro volný čas</p>  <p>• Další finanční bonusy a příplatky (měsíční, pololetní, osobní ohodnocení, při pracovních a životních výročích, za zlepšení, za doporučení nového zaměstnance (až do výše 20 000 Kč), za mimořádné, odpolední či noční směny či směny ve svátek, za pracovní pohotovost či dlouhodobé zastupování kolegy...)</p>  <p>• Podporu mobility - náhradu výdajů na dojíždění (firemní autobus nebo příspěvek na dojíždění po dobu až 6ti měsíců ve výši 500 - 6 500 Kč/měsíc), ubytování (až 6 500 Kč po dobu až 4 měsíců) a stěhování (až do výše 15 000 Kč)</p>  <p>• Příspěvek na penzijní připojištění 5 % z hrubé mzdy po zkušební době</p>']],
    ['nazev' => 'Inženýr kvality','kategorie' => [2],'mistoVykonu' => 'Žebrák','vzdelani' =>5,'popisPozice' => '<p>• Definovat, sledovat a řídit plán zlepšování jakosti</p>  <p>• Definovat prototyp, předsériový a sériový plán</p>  <p>• Podílet se na revizi designu</p>  <p>• Aktualizovat dokumenty kvality</p>  <p>• Revidovat kontrolní plán po problému nebo výsledcích testů</p>  <p>• Podílet se na analýze rizik - procesních i produktových</p>  <p>• Nastavovat a kontrolovat nové i stávající výrobní procesy z pohledu kvality</p>  <p>• Připravovat dokumentaci k prvním vzorkům (PPAP)</p>','pozadujeme' => ['<p>• SŠ, VŠ (ideálně zaměření na management jakosti, technického směru)</p>  <p>• Praxi v oblasti řízení kvality</p>  <p>• Výbornou znalost práce na PC</p>  <p>• Znalost moderních metod řízení jakosti - kontrolní a validační plány, FMEA, PPAP</p>  <p>• Aktivní znalost anglického jazyka</p>'],'nabizime' => ['<p>• 6 týdnů dovolené</p>  <p>• Bonusy závislé na výsledcích týmu</p>  <p>• Podpora na dojíždění: 3Kč/km (max. 6 000 Kč/měsíc)</p>  <p>• Příspěvek na penzijní připojištění 5 % z hrubé mzdy</p>  <p>• Dotovanou kantýnu</p>  <p>• Příspěvek na sport a volnočasové aktivity ve formě poukázek FlexiPass, v hodnotě 20000 Kč ročně</p>']],
    ['nazev' => '3D CAD konstruktér','kategorie' => [3],'mistoVykonu' => 'Praha','vzdelani' =>7,'popisPozice' => 'Ve vývojovém centru Valeo v Praze navrhujeme klimatizační jednotky do aut již od roku 2002. V roce 2020 vznikl v Praze nový vývojový tým zabývající se vysokonapěťovými komponenty do klimatizací elektromobilů a do systému chlazení jejich baterií. Tito mechaničtí, testovací a systémoví inženýři posílají své vyvinuté díly do 28 výrobních závodů po celém světě. Blíže pak spolupracují s vývojovým centrem ve francouzském La Verrière. Své projekty si řídí sami a vzhledem k inovativnosti jejich produktů jsou průkopníky na trhu elektromobility.','pozadujeme' => ['<p>• vysokoškolské vzdělání v technickém oboru</p>  <p>• zkušenost na podobné pozici je výhodou</p>  <p>• znalost softwaru Catia V5 nebo jiného nástroje 3D konstrukce</p>  <p>• angličtinu na dobré úrovni pro každodenní komunikaci v mezinárodním týmu</p>'],'nabizime' => ['<p>• 6 týdnů dovolené</p>  <p>• Možnost home-office</p>  <p>• Bonusy závislé na výsledcích týmu</p>  <p>• Podporu mobility (náhrada výdajů na dojíždění, stěhování, dočasné ubytování)</p>  <p>• Příspěvek na penzijní připojištění 5 % z hrubé mzdy</p>  <p>• Stravenky a výbornou kantýnu</p>  <p>• Příspěvek na sport ve formě poukázek FlexiPass nebo Multisport karty</p>  <p>• Technická a jazyková školení</p>']],
    ['nazev' => 'Logistik','kategorie' => [2],'mistoVykonu' => 'Žebrák','vzdelani' =>7,'popisPozice' => '<p>• Koordinace všech CIM aktivit pro nové projekty - od nominace až po sériovou výrobu, podpora týmu.</p>  <p>• Spolupráce s projektem na implementaci všech Valeo standardů pro nové projekty, vytváření nových standardů pro nové technologie.</p>  <p>• Koordinace všech činností z pohledu logistiky pro nové produkty spravované projektovými týmy z hlediska materiálových toků (interních i externích) a uskladnění , uspořádání v layoutu závodu, spolupráce se skladem a plánovacím týmem.</p>  <p>• Koordinace externího skladu a efektivita skladování - skladovací kapacita, snížení nákladů na skladování.</p>  <p>• Odpovědnost za implementaci a podporu současných technologií AGV v logistice.</p>','pozadujeme' => ['<p>• Zkušenost v logistice a automotive je velkou výhodou</p>  <p>• Analytické myšlení, dobré komunikační dovednosti</p>  <p>• Základní znalost CAD, SolidWorks</p>  <p>• Základní znalost SAP</p>  <p>• Anglický jazyk</p>'],'nabizime' => ['<p>• 6 týdnů dovolené</p>  <p>• Možnost home-office</p>  <p>• Bonusy závislé na výsledcích týmu</p>  <p>• Podpora na dojíždění: 3Kč/km (max. 6 000 Kč/měsíc)</p>  <p>• Příspěvek na penzijní připojištění 5 % z hrubé mzdy</p>  <p>• Dotovanou kantýnu</p>  <p>• Příspěvek na sport a volnočasové aktivity ve formě poukázek FlexiPass, v hodnotě 20000 Kč ročně</p>']],
    
    
]


?>

    <div id="pracovni-pozice">
       <?php
       
        
        include Configuration::componentControler()['templates']."presenter-job/template.php";
        ?>
    </div>