<?php
use Site\Configuration;
use Model\Arraymodel\EventList;

use Pes\View\Renderer\PhpTemplateRendererInterface;
use Model\Entity\PaperAggregatePaperContentInterface;

$headline = 'Pracovní pozice';
$perex = '';

//template:
//    repeat('vnitřek', $kategorie]
//$tag = [
//    1 => 'výroba/dělnická',
//    2 => 'administrativa/THP',
//    3 => 'technická',
//    4 => 'manažerská/vedoucí'
//];
//$kvalifikace = [
//    1 => 'Bez omezení',
//    2 => 'ZŠ',
//    3 => 'SOU bez maturity',
//    4 => 'SOU s maturitou',
//    5 => 'SŠ',
//    5 => 'VOŠ / Bc.',
//    5 => 'VŠ',
//];

$pracovniPozice = [
    
    ['nazev' => 'Strojní technik','kategorie' => [3],'mistoVykonu' => 'Chotěšov','vzdelani' =>5,'popisPozice' => '<p>Seřizování, uvádění a uvolňování nových strojů do provozu</p>  <p>Testování technologických procesů</p>  <p>Spolupráce napříč organizací při vývoji nových postupů</p>  <p>Komunikace s techniky z vývoje v Německu</p>  <p>Hledání technických řešení</p>  <p>Přejímky a zkoušky nových zařízen</p>','pozadujeme' => ['<p>• Znalosti minimálně na úrovni SŠ, strojní nebo elektro obor</p>  <p>• Znalost výkresové dokumentace a elektrických schémat</p>  <p>• Mít zájem o moderní techniku</p>  <p>• Angličtina nebo němčina na komunikativní úrovni</p>'],'nabizime' => ['<p>• Čekají Vás letní a zimní prémie</p>  <p>• Čisté a moderní prostředí</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Benefit program Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>']],
    ['nazev' => 'Manažer přípravy a plánování výroby','kategorie' => [4],'mistoVykonu' => 'Chotěšov','vzdelani' =>5,'popisPozice' => '<p>Zajištění krátkodobých, střednědobých a dlouhodobých výrobních kapacit v souvislosti s aktuálními požadavky zákazníka a na plánované projekty - kooperace s centrálou</p>  <p>Plánování personálních kapacit výroby</p>  <p>Plánování výrobních ploch - tvorba layoutů</p>  <p>Zajištění technické přípravy a dokumentace, správa pravidel přiřazení artiklů na výrobní linie</p>  <p>Sledování vytížení strojů a zařízení</p>  <p>Správa plánovacího katalogu pro celou MD skupinu</p>  <p>Řízení koordinace, rozvoj a motivace pracovníků daného úseku</p>  <p>Účast na nových projektech vedoucích k optimalizacím výrobních procesů</p>','pozadujeme' => ['<p>• Minimálně SŠ vzdělání</p>  <p>• Angličtina nebo němčina na komunikativní úrovni</p>  <p>• Znalost programu MS Excel a SAP</p>  <p>• Metody normování práce</p>  <p>• Praxe na obdobné pozici minimálně 2 roky</p>  <p>• Samostatný, strukturovaný způsob práce a smysl pro zodpovědnost</p>  <p> </p>  <p>• Výhodou bude pokud budete znát AutoCAD a španělský nebo bulharský jazyk</p>'],'nabizime' => ['<p>• Čisté a moderní prostředí</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Benefit program Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>']],
    ['nazev' => 'Manažer správy výrobního systému','kategorie' => [4],'mistoVykonu' => 'Chotěšov','vzdelani' =>5,'popisPozice' => '<p>Vyhodnocení vytížení jednotlivých výrobních linií, přiřazování artiklů na výrobní linie, správa a orientace v katalogu výrobních kódů</p>  <p>Podpora výroby v oblasti SAP, Topflow, Simple, funkce Keyuser</p>  <p>Správa systému, nastavení systému a vyhodnocení efektivnosti při zpracování speciálních zakázek, obsoletparts – návrhy na následné zpracování těchto dílů, správa centra tisku speciálních etiket</p>  <p>Kapacitní plánování v SAP, podpora kolegů z centrály</p>  <p>Kooperace na projektu zavedení "Umělé inteligence"</p>  <p>Vedení a rozvoj pracovníků ve svěřené oblasti, spolupráce s pracovníky napříč odděleními</p>  <p>Hospodárně využívat firemní zdroje ve svěřeném úseku</p>  <p>Řízení a minimalizace rizik</p>','pozadujeme' => ['<p>• Minimálně SŠ vzdělání</p>  <p>• Angličtina nebo němčina na komunikativní úrovni</p>  <p>• Znalost programu MS Excel a SAP</p>  <p>• Praxe na obdobné pozici minimálně 2 roky</p>  <p>• Samostatný, strukturovaný způsob práce a smysl pro zodpovědnost</p>'],'nabizime' => ['<p>• Čisté a moderní prostředí</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Benefit program Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>']],
    ['nazev' => 'Technik laboratoře','kategorie' => [3],'mistoVykonu' => 'Chotěšov','vzdelani' =>4,'popisPozice' => '<p>Provádění laboratorních činností, analýz a jejich vyhodnocování</p>  <p> </p>  <p>Údržba přidělených zařízení v rámci laboratoře</p>  <p> </p>  <p>Specializace na vysokofrekvenční zkoušky a elektrické testování</p>  <p> </p>  <p>Přímá účast na validování produktů a materiálů</p>  <p> </p>  <p>Komunikace napříč organizací a podpora chodu laboratoře</p>','pozadujeme' => ['<p>• Podmínkou je minimálně SOU vzdělání s elektro zaměřením</p>  <p>• Vyhláška 50/1978 Sb. §5 (lze obnovit/ rozšířit)</p>  <p>• Nebát se komunikovat telefonicky a písemně v angličtině</p>  <p>•Umět pracovat s Excelem na pokročilé úrovni</p>  <p>• Dobré analytické schopnosti</p>'],'nabizime' => ['<p>• Čekají Vás letní a zimní prémie</p>  <p>• Čisté a moderní pracoviště</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Máme pro Vás Benefit program Cafeteria Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>  <p>• Možnost seznámit se s širokým spektrem technologií</p>']],
    ['nazev' => 'Vedoucí projektů','kategorie' => [3],'mistoVykonu' => 'Chotěšov','vzdelani' =>5,'popisPozice' => '<p>Plánování a řízení projektů od fáze pořízení dílů, montáže až po předání zákazníkovi</p>  <p> </p>  <p>Kontrola finančních ukazatelů zadaného projektu</p>  <p> </p>  <p>Organizace přejímek a uvedení do provozu</p>  <p> </p>  <p>Spolupráce s různými odděleními v rámci celé skupiny MD</p>  <p> </p>  <p>Technická podpora výroby</p>  <p> </p>  <p>Zodpovědnost za dodržení termínů zadaného projektu</p>','pozadujeme' => ['<p>• VŠ\SŠ vzdělání technického zaměření</p>  <p>• Požadovaná praxe na obdobné pozici minimálně 2 roky</p>  <p>• Znalost anglického nebo německého jazyka na komunikativní úrovni</p>  <p>• Dobrou znalost MS Office a programu SAP</p>  <p>• Zkušenosti se stavbou strojů</p>  <p>• Manažerská kreativita – praktické zkušenosti s projektovým řízením a s řízením vývojových projektů</p>'],'nabizime' => ['<p>• Čisté a moderní prostředí</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Benefit program Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>']],
    ['nazev' => 'Manažer technického servisu','kategorie' => [4,3],'mistoVykonu' => 'Chotěšov','vzdelani' =>5,'popisPozice' => '<p>Odpovědnost za dodávky výrobních zařízení do skupiny MD</p>  <p>Korekce a spolutvorba specifikací nakupovaných zařízení</p>  <p>Koordinace přejímek/instalace/školení k svěřeným zařízením v rámci celé skupiny MD</p>  <p>Koordinace záručního/pozáručního servisu v rámci celé skupiny MD + evidence v SAP</p>  <p>Optimalizace zařízení a dohled nad dodržováním procesu optimalizace zařízení</p>  <p>Kontrola správného a hospodárného využívání výrobních zařízení (strojů, nástrojů a přípravků) a případné zjednání technologické kázně</p>  <p>Sledování klíčových ukazatelů svěřených zařízení (výpadek, využití, provozní náklady, kvalita) a stanovení vhodných opatření pro jejich pozitivní trend</p>  <p>Podpora ostatních závodů</p>','pozadujeme' => ['<p>• SŠ nebo VŠ technického směru</p>  <p>• Němčina a angličtina na komunikativní úrovni</p>  <p>• Zkušenost z obdobné pozice v automotive min. 5 let ( obdobné pozice: technický manager, manager údržby, manager servisu)</p>  <p>• Schopnost motivovat a vést tým podřízených</p>  <p>• Orientaci na úkoly a dosažení výsledků</p>  <p>• Samostatnou, vyzrálou a pečlivou osobnost</p>'],'nabizime' => ['<p>• Čisté a moderní pracoviště</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Benefit program Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>']],
    ['nazev' => 'Servisní technik','kategorie' => [3],'mistoVykonu' => 'Chotěšov','vzdelani' =>4,'popisPozice' => '<p>Přejímky systémů u dodavatelů a jejich následná instalace</p>  <p> </p>  <p>Účast na školeních u nových systémů a předávání znalostí výrobnímu personálu</p>  <p> </p>  <p>Servis vybavení v rámci skupiny MD (CZ, MX, BG, CN)</p>  <p> </p>  <p>Technická podpora ostatních útvarů společnosti</p>  <p> </p>  <p>Sledování efektivity, kvality a provozních nákladů svěřené skupiny zařízení</p>  <p> </p>  <p>Zprostředkování externího servisu a dohled nad jeho provedením</p>','pozadujeme' => ['<p>• Minimálně SOU vzdělání se zaměřením na elektro nebo strojírenství</p>  <p>• Znalost anglického nebo německého jazyka na komunikativní úrovni</p>  <p>• Vyhláška 50/1978 Sb. §5 (lze obnovit/ rozšířit)</p>  <p>• Samostatný, strukturovaný způsob práce a smysl pro zodpovědnost, technické myšlení</p>  <p>• Ochotu cestovat a vzdělávat se</p>'],'nabizime' => ['<p>• Čekají Vás letní a zimní prémie</p>  <p>• Čisté a moderní pracoviště</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Máme pro Vás Benefit program Cafeteria Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>']],
    ['nazev' => 'Referent nákupu','kategorie' => [2],'mistoVykonu' => 'Chotěšov','vzdelani' =>5,'popisPozice' => '<p>Denní komunikace s dodavateli ohledně objednávek, dodávek, urgencí a posunů termínů</p>  <p>Vyjasňování cenových odchylek při fakturaci</p>  <p>Kooperace s odděleními plánování výroby a plánování zakázek</p>  <p>Úzká spolupráce s oddělením kvality ohledně reklamací a hodnocení dodavatelů</p>  <p>Práce v programu SAP</p>','pozadujeme' => ['<p>• Znalosti minimálně na úrovni středoškolského vzdělání ekonomického nebo technického směru</p>  <p>• Komunikovat jak písemně tak telefonicky v němčině nebo angličtině</p>  <p>• Mít praxi v oboru minimálně 2 roky ideálně z Automotive</p>  <p>• Znalost ERP systému, ideálně SAP</p>  <p>• Vyjednávací schopnosti a schopnost organizace aktivit</p>  <p>• Být týmový hráč se schopností budovat vztahy uvnitř i vně společnosti</p>'],'nabizime' => ['<p>• Čisté a moderní prostřední</p>  <p>• Pouze ranní směnu</p>  <p>• Letní a zimní prémie</p>  <p>• Částečně pružnou pracovní dobu</p>  <p>• Benefit program Sodexo</p>  <p>• Až pět týdnů dovolené</p>  <p>• Na oběd můžete zajít do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>  <p>• Vlastní autobusovou dopravu z Horšovského Týna, Přeštic, Plzně, Klatov a Stříbra</p>']],
    ['nazev' => 'Manažer technického servisu - Vstřikování plastů','kategorie' => [4,3],'mistoVykonu' => 'Chotěšov','vzdelani' =>5,'popisPozice' => '<p>Vedení, motivace a rozvoj zaměstnanců ve svěřeném úseku</p>  <p>Udržování stabilního chodu strojového parku vstřikovny</p>  <p>Dohled nad technologickou kázní a správností nastavovacích podkladů</p>  <p>Organizace vlastního či externího servisu</p>  <p>Sledování ukazatelů procesu a provozních nákladů</p>  <p>Zavádění optimalizací procesu či zařízení</p>  <p>Účast na procesu validace vstřikovacích forem</p>  <p>Řízení údržby vstřikovacích forem</p>  <p>Dohled nad školením seřizovačů</p>','pozadujeme' => ['<p>• SŠ / VŠ technického směru</p>  <p>• Minimálně 5 let praxe v oblasti vstřikování plastů (automotive výhodou)</p>  <p>• Znalost vstřikovacích forem a technologických procesů z oblasti vstřikování plastů</p>  <p>• Zkušenost s nastavováním parametrů a odstraňováním vad produktu - rozměry/vzhled/tvar</p>  <p>• Schopnost navrhovat řešení problémů</p>  <p>Angličtina nebo němčina na komunikativní úrovni</p>  <p>• Řídící a organizační schopnosti</p>'],'nabizime' => ['<p>• Čisté a moderní pracoviště</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Benefit program Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>']],
    ['nazev' => 'Skladník technického materiálu','kategorie' => [1,3],'mistoVykonu' => 'Chotěšov','vzdelani' =>5,'popisPozice' => '<p>Zadávání objednávek od externích dodavatelů do SAPu a příjem dílů</p>  <p>Příjem a kontrola přijímaných zásilek</p>  <p>Vizuální kontrola dílů a práce s technickou dokumentací</p>  <p>Naskladnění zboží do skladových pozic a jejich vyskladnění dle požadavků</p>  <p>Příprava expedice zakázek do závodů MD</p>  <p>Spolupráce při provádění inventur</p>  <p>Obsluha manipulační techniky</p>','pozadujeme' => ['<p>• Minimálně SŠ vzdělání</p>  <p>• Znalost technických výkresů a programu SAP</p>  <p>• Samostatný, strukturovaný způsob práce a smysl pro zodpovědnost</p>  <p>• Pozice skladníka technického materiálu je na 2 směny (ranní a odpolední).</p>'],'nabizime' => ['<p>• Čekají Vás letní a zimní prémie</p>  <p>• Čisté a moderní prostředí</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Máme pro Vás Benefit program Cafeteria Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>']],
    ['nazev' => 'Datový analytik','kategorie' => [2,3],'mistoVykonu' => 'Chotěšov','vzdelani' =>5,'popisPozice' => '<p>Analýza prostojů a chyb v automatizovaných linkách</p>  <p>Stanovení metodiky sběru dat a jejich vyhodnocování</p>  <p>Práce s datovými vstupy a výstupy</p>  <p>Hledání a využití nových datových zdrojů</p>  <p>Navrhovat zlepšení procesů, vytvářet reporty</p>  <p>Spolupráce s kolegy napříč organizací</p>','pozadujeme' => ['<p>• Minimálně SŠ technického směru</p>  <p>• Programování v SQL nebo Python</p>  <p>• Zkušenost v data managementu</p>  <p>• Excel na pokročilé úrovni</p>  <p>• Angličtinu nebo němčinu na komunikativní úrovni</p>  <p>• Samostatný, strukturovaný způsob práce a smysl pro zodpovědnost</p>  <p>• Praxi na podobné pozici minimálně rok</p>'],'nabizime' => ['<p>• Čekají Vás letní a zimní prémie</p>  <p>• Čisté a moderní prostředí</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Máme pro Vás Benefit program Cafeteria Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>']],
    ['nazev' => 'Inženýr zákaznické kvality','kategorie' => [2,3],'mistoVykonu' => 'Chotěšov','vzdelani' =>5,'popisPozice' => '<p>Komunikace se zákazníkem a řešení zákaznických reklamací</p>  <p>Tvorba 8D reportů</p>  <p>Analýza příčin a definice opatření k zákaznickým reklamacím</p>  <p>Podílet se na revizích FMEA a je-li to potřeba, upravovat je</p>  <p>Příprava a účast při zákaznických návštěvách a telekonferencích</p>  <p>Školení personálu ve vztahu k 8D a jeho analýzám a opatřením, školení zákaznických požadavků</p>','pozadujeme' => ['<p>• Minimálně SŠ vzdělání</p>  <p>• Znalost automotive prostředí a “nástrojů kvality“ (8D, SPC, FMEA, APQP, PPAP)</p>  <p>• Samostatný, strukturovaný způsob práce a smysl pro zodpovědnost</p>  <p>• Angličtinu na komunikativní úrovni (NJ výhodou)</p>  <p>• Praxi na podobné pozici minimálně rok</p>'],'nabizime' => ['<p>• Čekají Vás letní a zimní prémie</p>  <p>• Čisté a moderní prostředí</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Máme pro Vás Benefit program Cafeteria Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>']],
    ['nazev' => 'Krimpovací technik','kategorie' => [3],'mistoVykonu' => 'Chotěšov','vzdelani' =>5,'popisPozice' => '<p>Montáž a kompletace krimpovacích nástrojů dle výkresové dokumentace</p>  <p> </p>  <p>Detailní nastavení nástrojů, následný servis a údržba</p>  <p> </p>  <p>Instalace a oživování krimpovacích nástrojů v automatizované lince</p>  <p> </p>  <p>Technická podpora ostatních útvarů v oddělení</p>  <p> </p>  <p>Měření krimpovací síly lisu a celkového odladění nástroje v automatizované lince</p>','pozadujeme' => ['<p>• Minimálně SŠ technického směru</p>  <p>• Znalost anglického nebo německého jazyka na komunikativní úrovni</p>  <p>• Znalost výkresové dokumentace a znalost pneumatiky</p>  <p>• Samostatný, strukturovaný způsob práce a smysl pro zodpovědnost, technické myšlení</p>'],'nabizime' => ['<p>• Čekají Vás letní a zimní prémie</p>  <p>• Čisté a moderní prostředí</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Máme pro Vás Benefit program Cafeteria Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>']],
    ['nazev' => 'PLC programátor','kategorie' => [3],'mistoVykonu' => 'Chotěšov','vzdelani' =>5,'popisPozice' => '<p>Vývoj automatizovaných výrobních linek a jednoúčelových strojů</p>  <p> </p>  <p>Tvorba programů pro řízení jednoúčelových strojů a výrobních linek</p>  <p> </p>  <p>Uvádění do provozu strojů a výrobních linek</p>  <p> </p>  <p>Spolupráce s kolegy z ostatních oddělení (konstrukce, elektrokonstrukce, montáž)</p>  <p> </p>  <p>Diagnostika</p>','pozadujeme' => ['<p>• SŠ nebo VŠ v oboru elektro</p>  <p>• Znalost programování řídicích systémů, především PLC Simatic (TIA portal)</p>  <p>• Schopnost orientovat se v elektroschématech</p>  <p>• Angličtina nebo němčina na komunikativní úrovni</p>  <p>• Samostatný, strukturovaný způsob práce a smysl pro zodpovědnost, analytické a logické myšlení,</p>  <p>• Vyhláška 50/1978 Sb. §6 (může být i propadlá, pokud máte §5 můžete u nás rozšířit)</p>'],'nabizime' => ['<p>• Čekají Vás letní a zimní prémie</p>  <p>• Čisté a moderní prostředí</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Máme pro Vás Benefit program Cafeteria Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>']],
    ['nazev' => 'Plánovač / Normovač','kategorie' => [2,3],'mistoVykonu' => 'Chotěšov','vzdelani' =>5,'popisPozice' => '<p>Budete provádět a vyhodnocovat časové snímky</p>  <p>Spolupracovat s kolegy z Německa při vytváření "Plánovacího katalogu časů"</p>  <p>Sledovat využívání výrobních linek</p>  <p>Kontrolovat dodržování výrobních postupů a procesů</p>  <p>Budete spolupracovat s kolegy napříč organizací při vytváření nových pracovišť, optimalizovat stávající pracoviště z hlediska ergonomie</p>  <p>Vyhledávat možnosti neustálého zlepšování</p>','pozadujeme' => ['<p>• SŠ vzdělání, školení REFA</p>  <p>• Komunikativní znalost anglického nebo německého jazyka</p>  <p>• Znalost metod normování práce a principů štíhlé výroby</p>  <p>• Samostatný, strukturovaný způsob práce a • smysl pro zodpovědnost</p>  <p>• Praxe na obdobné pozici minimálně 2 roky</p>'],'nabizime' => ['<p>• Čekají Vás letní a zimní prémie</p>  <p>• Čisté a moderní prostředí</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Máme pro Vás Benefit program Cafeteria Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>']],
    ['nazev' => 'Pracovník zákaznických objednávek','kategorie' => [2],'mistoVykonu' => 'Chotěšov','vzdelani' =>5,'popisPozice' => '<p>Správa zákaznických objednávek (zadávání, úpravy a kontroly)</p>  <p> </p>  <p>Vyřízení a aplikace zvláštních zákaznických požadavků</p>  <p> </p>  <p>Analýza skladových zásob a jejich optimalizace</p>  <p> </p>','pozadujeme' => ['<p>• Minimálně SŠ vzdělání</p>  <p>• Zkušenosti z oblasti vyřizování zákaznických objednávek</p>  <p>• Znalost anglického jazyka na komunikativní úrovni německý jazyk výhodou</p>  <p>• Samostatný, strukturovaný způsob práce a smysl pro zodpovědnost</p>  <p>• Výborné organizační a komunikační dovednosti</p>  <p>• SAP nebo jiný ERP</p>'],'nabizime' => ['<p>• Čekají Vás letní a zimní prémie</p>  <p>• Čisté a moderní prostředí</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Máme pro Vás Benefit program Cafeteria Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>']],
    ['nazev' => 'Technik kamerových systémů','kategorie' => [3],'mistoVykonu' => 'Chotěšov','vzdelani' =>5,'popisPozice' => '<p>Zajímavá a kreativní činnost při používání znalostí z oblasti zpracování obrazu, robotiky, komunikační a testovací techniky.</p>  <p> </p>  <p>Instalace a oživení kamerových systémů</p>  <p> </p>  <p>Spolupráce při uvádění výrobních linek do provozu</p>  <p> </p>  <p>Komunikace s techniky z ostatních oddělení včetně naší centrály v Německu</p>','pozadujeme' => ['<p>• Ukončené vzdělání v oboru elektrotechnika, informatika, mechatronika</p>  <p>• Angličtina nebo němčina na komunikativní úrovni</p>  <p>• Samostatnost, spolehlivost, zodpovědnost</p>  <p>• Zájem učit se nové věci a snaha posouvat se vpřed</p>'],'nabizime' => ['<p>• Čekají Vás letní a zimní prémie</p>  <p>• Čisté a moderní prostředí</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Máme pro Vás Benefit program Cafeteria Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>']],
    ['nazev' => 'Konstruktér','kategorie' => [2,3],'mistoVykonu' => 'Chotěšov','vzdelani' =>5,'popisPozice' => '<p>Vývoj a mechanická konstrukce automatizovaných výrobních a testovacích zařízení</p>  <p> </p>  <p>Návrhy a optimalizace konstrukčních prvků a skupin</p>  <p> </p>  <p>Vytváření konstrukční a projektové dokumentace</p>  <p> </p>  <p>Technická podpora výroby a údržby</p>','pozadujeme' => ['<p>• Vzdělání v oboru strojírenství nebo elektro</p>  <p>• Znalost SolidWorks nebo jiného CAD</p>  <p>• Německý nebo anglický jazyk na komunikativní úrovni</p>'],'nabizime' => ['<p>• Čekají Vás letní a zimní prémie</p>  <p>• Čisté a moderní prostředí</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Máme pro Vás Benefit program Cafeteria Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>']],
    ['nazev' => 'Pracovník technické dokumentace','kategorie' => [3,2],'mistoVykonu' => 'Chotěšov','vzdelani' =>5,'popisPozice' => '<p>Podpora při zpracování dokumentace</p>  <p>Správa dokumentace oddělení konstrukce</p>  <p>Kreslení jednoduchých výkresů</p>','pozadujeme' => ['<p>• SŠ vzdělání v oboru</p>  <p>• Komunikativní znalost anglického nebo německého jazyka</p>  <p>• Znalost práce v některém z používaných CAD programů, nejlépe Solidworks</p>  <p>• Samostatný, strukturovaný způsob práce a smysl pro zodpovědnost, technické myšlení</p>'],'nabizime' => ['<p>• Čekají Vás letní a zimní prémie</p>  <p>• Čisté a moderní prostředí</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Máme pro Vás Benefit program Cafeteria Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>•Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>']],
    ['nazev' => 'Procesní technik - správa a zlepšování procesů','kategorie' => [2,3],'mistoVykonu' => 'Chotěšov','vzdelani' =>5,'popisPozice' => '<p>Dohled nad stávajícími procesy a pracovními postupy a jejich vyhodnocování</p>  <p> </p>  <p>Vyhledávat možnosti zlepšování výrobních procesů</p>  <p> </p>  <p>Sledovat hodnoty interní výpadkovosti, hledat opatření ke snížení této hodnoty</p>  <p> </p>  <p>Testovat nové materiály pro výrobu</p>  <p> </p>  <p>Spolupráce na vývoji a integrace nových projektů</p>  <p> </p>  <p>Posuzování a zlepšování ergonomických aspektů procesů</p>  <p> </p>  <p>Sledování efektivity údržby, spolupráce při tvorbě a optimalizaci plánu údržby</p>','pozadujeme' => ['<p>• Minimálně SŠ nebo VŠ vzdělání (strojního nebo elektrotechnického směru)</p>  <p>• Znalost anglického nebo německého jazyka na komunikativní úrovni</p>  <p>• Uživatelská znalost MS Office (zejména Excel) a programu SAP</p>  <p>• Samostatný, strukturovaný způsob práce a smysl pro zodpovědnost, technické myšlení</p>  <p>• Praxe na obdobné pozici minimálně 2 roky a ochotu cestovat do zahraničí</p>'],'nabizime' => ['<p>• Čekají Vás letní a zimní prémie</p>  <p>• Čisté a moderní prostředí</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Máme pro Vás Benefit program Cafeteria Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>']],
    ['nazev' => 'Seřizovač / mechanik','kategorie' => [3],'mistoVykonu' => 'Chotěšov','vzdelani' =>3,'popisPozice' => '<p>Seřizování a příprava strojů ve výrobě dle aktuální zakázkové náplně</p>  <p>Údržby a drobné opravy na svěřeném výrobním oddělení</p>  <p>Kontrola strojů pro jednotlivé pracovníky</p>  <p>Preventivní údržba strojů, optimalizace procesů</p>','pozadujeme' => ['<p>• Vyučení ve strojírenském / elektro oboru nebo technickém oboru</p>  <p>• Znalost mechanických oprav, nutná předchozí praxe</p>  <p>• Manuální zručnost, odpovědnost, schopnost samostatné práce</p>  <p>• Práce v turnusovém provozu (příp. třísměnném provozu)</p>  <p>• Praxe s jemnou mechanikou a pneumatikou výhodou</p>  <p>• Vhodné i pro uchazeče se znalostí vstřikování plastů</p>  <p>• Vhodné pro absolventy technických škol</p>'],'nabizime' => ['<p>• Čekají Vás letní a zimní prémie</p>  <p>• Čisté a moderní prostředí</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Máme pro Vás Benefit program Cafeteria Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>']],
    ['nazev' => 'Elektrikář','kategorie' => [3],'mistoVykonu' => 'Chotěšov','vzdelani' =>3,'popisPozice' => '<p>Provádění rozvodů kabeláže a zapojení nových strojů dle technických výkresů</p>  <p>Zapojení rozvaděčů</p>  <p>Montáž, zapojení a oživení všech elektrických komponentů a periferií</p>  <p>Spolupráce při instalaci a uvádění do provozu s kolegy (PLC programátoři, mechanici montáže apod.)</p>  <p>Údržba a opravy stávajících výrobních strojů a zařízení</p>','pozadujeme' => ['<p>• Vzdělání v oboru elektro</p>  <p>• Platná vyhláška 50/1978 Sb., § 6 (samostatná činnost)</p>  <p>• Požadovaná praxe v oboru 2 roky</p>  <p>• Znalost výkresové dokumentace a elektrických schémat</p>  <p>• Výhodou je znalost pneumatiky a řízení strojů</p>  <p>• Uvítáme i znalost německého nebo anglického jazyka</p>  <p>• Schopnost samostatné práce a zodpovědný přístup ke svěřeným úkolům</p>  <p>• Práce na ranní a odpolední směny</p>'],'nabizime' => ['<p>• Čekají Vás letní a zimní prémie</p>  <p>• Čisté a moderní prostředí</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Máme pro Vás Benefit program Cafeteria Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>']],
    ['nazev' => 'Mechanik montáže','kategorie' => [3],'mistoVykonu' => 'Chotěšov','vzdelani' =>3,'popisPozice' => '<p>Montáž jednotlivých částí a celků výrobních zařízení</p>  <p>Výroba drobných dílů podle výkresové dokumentace (v elektronické formě) nebo podle individuální potřeby montáže</p>  <p>Instalace kabelů, snímačů, řídících a ovládacích prvků na výrobní zařízení</p>  <p>Údržba a opravy stávajících výrobních strojů a zařízení</p>  <p>Možnost výjezdů i do zahraničí na naše pobočky</p>  <p>Práce na ranní a odpolední směně</p>','pozadujeme' => ['<p>• Vyučen v oboru mechanik, mechatronik, zámečník a nástrojař</p>  <p>• 2 roky praxe v oboru a zkušenosti se seřizováním strojů</p>  <p>• Znalost výkresové dokumentace a praxe v montáži</p>  <p>• Znalost pneumatiky výhodou</p>  <p>• Výhodou je i znalost německého nebo anglického jazyka</p>  <p>• Pečlivost, samostatnost, zodpovědný přístup ke svěřené práci</p>'],'nabizime' => ['<p>• Čekají Vás letní a zimní prémie</p>  <p>• Čisté a moderní prostředí</p>  <p>• Částečně flexibilní pracovní doba</p>  <p>• Až 5 týdnů dovolené</p>  <p>• Máme pro Vás Benefit program Cafeteria Sodexo</p>  <p>• Na oběd můžete do naší firemní kantýny</p>  <p>• Možnost profesního rozvoje absolvováním odborných a jazykových školení</p>']],
    
]


?>

    <div id="pracovni-pozice">
       <?php
       
        
        include Configuration::componentControler()['templates']."presenter-job/template.php";
        ?>
    </div>